bot_uin: '123456' # Bot QQ 号，请修改为机器人的 QQ 号
root: '123456' # Bot 管理员 QQ 号，请修改为你的 QQ 号
debug: false # 调试模式, 开启将会打印更多调试信息
enable_webui_interaction: true # 启用 webui 交互
check_ncatbot_update: true # 检查 NcatBot 更新
skip_ncatbot_install_check: false # 跳过 NcatBot 安装检查
websocket_timeout: 15

napcat:
  ws_uri: ws://localhost:3001
  ws_token: napcat_ws
  webui_uri: http://localhost:6099
  webui_token: napcat_webui
  enable_webui: true
  skip_setup: false # 设为 true 则跳过 NapCat 安装直接连接
  enable_update_check: false

plugin:
  plugins_dir: plugins
  load_plugin: true
  auto_install_pip_deps: true
  plugin_whitelist: []
  plugin_blacklist: []

logging:
  event_log_levels:
    meta_event: NONE
    meta_event.lifecycle: DEBUG
